# -*- coding: utf-8 -*-
"""fin_gen_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1exFAxXYkdn2JMjlQ2nrj5fSj_NhgufMt
"""

from google.colab import drive
drive.mount('/content/drive')

cd '/content/drive/MyDrive/final_fingerprint_project'

from tensorflow.keras.models import model_from_json
json_file = open('gender_model_dout_reg_100.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("gender_model_dout_reg_100.h5")
print("Loaded model from disk")

# Making predictions on new data
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing import image

ls

temp = image.load_img('vinutha.bmp', target_size = (64, 64)) #convert the test image into array 64x64 dimensions
#imgplot = plt.imshow(temp)
temp = image.img_to_array(temp)#Keras provides the img_to_array() function for converting a loaded image into a NumPy array for use with deep learning models.
temp = np.expand_dims(temp, axis = 0)

result = loaded_model.predict(temp)#values are normalized and class is predicted against the model
result

if result[0][0] == 1:
 prediction = 'female'
 print(prediction)
elif result[0][1] == 1:
 prediction = 'male'
 print(prediction)

